//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeZone_Assign
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARD
    {
        public string CARD_ID { get; set; }
        public string CUSTOMER_ID { get; set; }
        public string CARD_NUMBER { get; set; }
        public string GOODTHRU { get; set; }
        public string CVV { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
