//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeZone_Assign
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DELIVERY()
        {
            this.ORDERS = new HashSet<ORDER>();
        }
    
        public string DELIVERY_ID { get; set; }
        public string SHIPPING_ADDRESS { get; set; }
        public Nullable<System.DateTime> EST_EARLIEST_DATE { get; set; }
        public Nullable<System.DateTime> EST_LATEST_DATE { get; set; }
        public Nullable<System.DateTime> ARRIVAL_DATE { get; set; }
        public string STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERS { get; set; }
    }
}
