//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeZone_Assign
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_ITEM
    {
        public string ORDER_ID { get; set; }
        public string WATCH_ID { get; set; }
        public string REVIEW_ID { get; set; }
        public int QTY { get; set; }
    
        public virtual ORDER ORDER { get; set; }
        public virtual REVIEW REVIEW { get; set; }
        public virtual WATCH WATCH { get; set; }
    }
}
