//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeZone_Assign
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER()
        {
            this.ORDER_ITEM = new HashSet<ORDER_ITEM>();
        }
    
        public string ORDER_ID { get; set; }
        public string CUSTOMER_ID { get; set; }
        public string PAYMENT_ID { get; set; }
        public string DELIVERY_ID { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual DELIVERY DELIVERY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_ITEM> ORDER_ITEM { get; set; }
        public virtual PAYMENT PAYMENT { get; set; }
    }
}
